/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ClipboardCopyError: typeof import('@moluoxixi/components/CopyText')['ClipboardCopyError']
  const copyText: typeof import('@moluoxixi/components/CopyText')['copyText']
  const createHeadlessTableRenderer: typeof import('@moluoxixi/components/HeadlessTable')['createHeadlessTableRenderer']
  const createHeadlessTableRendererPlugin: typeof import('@moluoxixi/components/HeadlessTable')['createHeadlessTableRendererPlugin']
  const defineHeadlessTableRenderer: typeof import('@moluoxixi/components/HeadlessTable')['defineHeadlessTableRenderer']
  const getHeadlessTableColumnId: typeof import('@moluoxixi/components/HeadlessTable')['getHeadlessTableColumnId']
  const getHeadlessTableColumnLabel: typeof import('@moluoxixi/components/HeadlessTable')['getHeadlessTableColumnLabel']
  const getHeadlessTableRawValue: typeof import('@moluoxixi/components/HeadlessTable')['getHeadlessTableRawValue']
  const headlessTableRenderer: typeof import('@moluoxixi/components/HeadlessTable')['headlessTableRenderer']
  const headlessTableRendererKey: typeof import('@moluoxixi/components/HeadlessTable')['headlessTableRendererKey']
  const provideHeadlessTableRenderer: typeof import('@moluoxixi/components/HeadlessTable')['provideHeadlessTableRenderer']
  const useHeadlessTable: typeof import('@moluoxixi/components/HeadlessTable')['useHeadlessTable']
}
