shellEmulator: true

trustPolicy: no-downgrade

packages:
  - 'packages/*'
  - 'packages/ConfigForm/*'
  - 'playgrounds/*'

catalogs:
  build:
    dayjs: ^1.11.20
    vue: ^3.5.13
  data:
    '@tanstack/vue-query': ^5.101.0
  dev:
    '@antfu/eslint-config': ^8.2.0
    '@babel/parser': ^7.28.5
    '@changesets/cli': ^2.31.0
    '@playwright/test': ^1.60.0
    '@vitejs/plugin-vue': ^5.2.3
    '@vitejs/plugin-vue-jsx': ^4.2.0
    '@vitest/coverage-v8': ^3.2.4
    '@vue/compiler-sfc': ^3.5.13
    '@vue/language-core': ~3.1.8
    '@vue/test-utils': ^2.4.10
    eslint: ^9.5.0
    eslint-plugin-format: ^2.0.1
    happy-dom: ^20.9.0
    husky: ^9.1.7
    jiti: ^2.6.1
    launch-editor: ^2.13.2
    lint-staged: ^17.0.5
    magic-string: ^0.30.17
    sass: ^1.85.0
    typescript: ^5.8.2
    unplugin-auto-import: ^19.1.2
    unplugin-dts: ^1.0.0
    unplugin-vue-components: ^28.4.1
    vite: ^6.2.0
    vitest: ^3.1.1
    vue-tsc: ^2.2.8
    zod: ^3.24.2
  type:
    '@types/node': ^25.6.0
  ui:
    ant-design-vue: ^4.2.6
    element-plus: ^2.9.1
