<script setup lang="ts">
import type { FormRuntimeOptions } from '@moluoxixi/config-form'
import { computed, reactive, ref } from 'vue'
import { z } from 'zod'
import {
  ConfigForm,
  defineField,
} from '@moluoxixi/config-form'
import {
  createI18nPlugin,
  type I18nMessages,
} from '@moluoxixi/config-form-plugin-i18n'
import { ElInput } from 'element-plus'
import { ElRadio, ElRadioGroup } from 'element-plus'
import { ElSelectV2 } from 'element-plus'

type Locale = 'zh-CN' | 'en-US'

const formRef = ref()
const formValues = reactive<Record<string, unknown>>({})
const locale = ref<Locale>('zh-CN')

const messages: I18nMessages = {
  'zh-CN': {
    'i18n.action.reset': '重置',
    'i18n.action.submit': '提交',
    'i18n.action.switchLocale': '切换到 {locale}',
    'i18n.action.validate': '校验',
    'i18n.custom.placeholder': '由 translate 自定义生成 label',
    'i18n.email.invalid': '请输入有效邮箱',
    'i18n.email.label': '邮箱',
    'i18n.email.placeholder': '请输入邮箱',
    'i18n.feedback.submitSuccess': '提交成功！',
    'i18n.feedback.validationFailed': '校验失败：',
    'i18n.gender.female': '女',
    'i18n.gender.label': '性别',
    'i18n.gender.male': '男',
    'i18n.gender.other': '其他',
    'i18n.locale.en': 'English',
    'i18n.locale.zh': '中文',
    'i18n.phone.label': '手机号',
    'i18n.phone.placeholder': '请输入手机号',
    'i18n.preview.title': '提交值快照',
    'i18n.role.admin': '管理员',
    'i18n.role.guest': '访客',
    'i18n.role.label': '角色',
    'i18n.role.placeholder': '请选择角色',
    'i18n.role.required': '请选择角色',
    'i18n.role.user': '用户',
    /**
     * 演示语言包函数消息。
     *
     * 只依赖当前 locale 返回 label，不读取外部表单状态。
     */
    'i18n.suggestion.label': (_params, currentLocale) => currentLocale === 'en-US' ? 'Suggestion' : '建议',
    'i18n.suggestion.placeholder': '函数消息 label + 插件 props 映射',
    'i18n.username.guestMin': '访客用户名至少 {min} 个字符',
    'i18n.username.label': '用户名（{min}-{max} 个字符）',
    'i18n.username.max': '用户名最多 {max} 个字符',
    'i18n.username.min': '用户名至少 {min} 个字符',
    'i18n.username.noSpace': '用户名不能包含空格',
    'i18n.username.placeholder': '请输入用户名',
  },
  'en-US': {
    'i18n.action.reset': 'Reset',
    'i18n.action.submit': 'Submit',
    'i18n.action.switchLocale': 'Switch to {locale}',
    'i18n.action.validate': 'Validate',
    'i18n.custom.placeholder': 'Label is generated by custom translate',
    'i18n.email.invalid': 'Please enter a valid email',
    'i18n.email.label': 'Email',
    'i18n.email.placeholder': 'Enter email',
    'i18n.feedback.submitSuccess': 'Submitted!',
    'i18n.feedback.validationFailed': 'Validation failed:',
    'i18n.gender.female': 'Female',
    'i18n.gender.label': 'Gender',
    'i18n.gender.male': 'Male',
    'i18n.gender.other': 'Other',
    'i18n.locale.en': 'English',
    'i18n.locale.zh': '中文',
    'i18n.phone.label': 'Phone',
    'i18n.phone.placeholder': 'Enter phone number',
    'i18n.preview.title': 'Submitted value snapshot',
    'i18n.role.admin': 'Admin',
    'i18n.role.guest': 'Guest',
    'i18n.role.label': 'Role',
    'i18n.role.placeholder': 'Select role',
    'i18n.role.required': 'Select a role',
    'i18n.role.user': 'User',
    /**
     * 演示语言包函数消息。
     *
     * 只依赖当前 locale 返回 label，不读取外部表单状态。
     */
    'i18n.suggestion.label': (_params, currentLocale) => currentLocale === 'en-US' ? 'Suggestion' : '建议',
    'i18n.suggestion.placeholder': 'Function message label + plugin props mapping',
    'i18n.username.guestMin': 'Guest username must be at least {min} characters',
    'i18n.username.label': 'Username ({min}-{max} chars)',
    'i18n.username.max': 'Username must be at most {max} characters',
    'i18n.username.min': 'Username must be at least {min} characters',
    'i18n.username.noSpace': 'Username cannot contain spaces',
    'i18n.username.placeholder': 'Enter username',
  },
}

/**
 * 渲染 playground 本地按钮文案模板。
 *
 * 只处理 `{key}` 形式的浅层 params，不覆盖 i18n 插件自身的字段文案解析。
 */
function renderTemplate(template: string, params?: Record<string, unknown>) {
  return template.replace(/\{([^}]+)\}/g, (_, key: string) => {
    const value = params?.[key.trim()]
    return value == null ? '' : String(value)
  })
}

/**
 * 读取当前 locale 的本地文案。
 *
 * 缺失 key 或非字符串消息会直接抛错，避免按钮文案静默退回错误内容。
 */
function t(key: string, params?: Record<string, unknown>) {
  const message = messages[locale.value]?.[key]
  if (message === undefined)
    throw new Error(`Missing local i18n message: ${key}`)
  if (typeof message !== 'string')
    throw new TypeError(`Local i18n helper only supports string messages: ${key}`)

  return renderTemplate(message, params)
}

/**
 * 将空字符串归一化为 undefined。
 *
 * 仅用于示例中的可选文本字段，非字符串值保持原样交给 schema。
 */
function emptyStringToUndefined(value: unknown) {
  if (typeof value !== 'string')
    return value

  const trimmed = value.trim()
  return trimmed.length === 0 ? undefined : trimmed
}

/**
 * 创建可选文本 schema。
 *
 * 先把空字符串转为 undefined，再执行传入字符串 schema 的校验。
 */
function optionalText(schema: z.ZodString = z.string()) {
  return z.preprocess(emptyStringToUndefined, schema.optional())
}

const runtimeOptions = {
  plugins: [
    createI18nPlugin({
      /** 每次转换字段时读取当前 playground locale。 */
      locale: () => locale.value,
      messages,
      fields: {
        username: {
          label: {
            key: 'i18n.username.label',
            defaultMessage: '用户名',
            params: { max: 20, min: 2 },
          },
          props: {
            placeholder: {
              key: 'i18n.username.placeholder',
              defaultMessage: '请输入用户名',
            },
          },
        },
        email: {
          label: { key: 'i18n.email.label', defaultMessage: '邮箱' },
          props: {
            placeholder: {
              key: 'i18n.email.placeholder',
              defaultMessage: '请输入邮箱',
            },
          },
        },
        role: {
          label: { key: 'i18n.role.label', defaultMessage: '角色' },
          props: {
            placeholder: {
              key: 'i18n.role.placeholder',
              defaultMessage: '请选择角色',
            },
          },
        },
        phone: {
          label: { key: 'i18n.phone.label', defaultMessage: '手机号' },
          props: {
            placeholder: {
              key: 'i18n.phone.placeholder',
              defaultMessage: '请输入手机号',
            },
          },
        },
        gender: {
          label: { key: 'i18n.gender.label', defaultMessage: '性别' },
        },
        suggestion: {
          label: { key: 'i18n.suggestion.label', defaultMessage: '建议' },
          props: {
            placeholder: {
              key: 'i18n.suggestion.placeholder',
              defaultMessage: '请输入建议',
            },
          },
        },
        custom: {
          label: {
            key: 'i18n.custom.label',
            defaultMessage: '自定义字段',
            params: { field: 'custom' },
          },
          props: {
            placeholder: {
              key: 'i18n.custom.placeholder',
              defaultMessage: '自定义 translate',
            },
          },
        },
      },
      /**
       * 演示自定义 translate hook。
       *
       * 仅接管 i18n.custom.label，其余 key 返回 undefined 继续走 messages 查找。
       */
      translate: (key, params, defaultMessage, currentLocale) => {
        if (key === 'i18n.custom.label') {
          const prefix = currentLocale === 'en-US' ? 'Custom field' : '自定义字段'
          const fieldName = params?.field
          if (fieldName == null)
            throw new Error(defaultMessage ?? `Missing custom field name: ${key}`)

          return `${prefix}: ${fieldName}`
        }
        return undefined
      },
    }),
  ],
} satisfies FormRuntimeOptions

const nextLocaleLabel = computed(() => locale.value === 'zh-CN'
  ? t('i18n.locale.en')
  : t('i18n.locale.zh'))

const fields = computed(() => [
  defineField({
    field: 'username',
    validateOn: ['blur', 'change'],
    schema: z.string()
      .min(2, t('i18n.username.min', { min: 2 }))
      .max(20, t('i18n.username.max', { max: 20 })),
    span: 12,
    component: ElInput,
    props: {
      clearable: true,
    },
    /**
     * 校验用户名与角色组合。
     *
     * 错误消息通过当前 locale 的本地文案生成。
     */
    validator: (value, values) => {
      if (values.role === 'guest' && value.length < 4)
        return t('i18n.username.guestMin', { min: 4 })

      return value.includes(' ') ? t('i18n.username.noSpace') : undefined
    },
    /** 提交前裁剪用户名空白，实时输入值保持不变。 */
    transform: value => value.trim(),
  }),
  defineField({
    field: 'email',
    validateOn: 'blur',
    schema: optionalText(z.string().email(t('i18n.email.invalid'))),
    span: 12,
    component: ElInput,
    props: {
      clearable: true,
    },
    transform: emptyStringToUndefined,
  }),
  defineField({
    field: 'role',
    schema: z.preprocess(emptyStringToUndefined, z.string().min(1, t('i18n.role.required')).optional()),
    span: 12,
    component: ElSelectV2,
    props: {
      clearable: true,
      options: [
        { label: t('i18n.role.admin'), value: 'admin' },
        { label: t('i18n.role.user'), value: 'user' },
        { label: t('i18n.role.guest'), value: 'guest' },
      ],
    },
  }),
  defineField({
    field: 'phone',
    schema: optionalText(),
    span: 12,
    component: ElInput,
    props: {
      clearable: true,
    },
    transform: emptyStringToUndefined,
  }),
  defineField({
    field: 'gender',
    schema: z.preprocess(emptyStringToUndefined, z.string().optional()),
    span: 12,
    component: ElRadioGroup,
    slots: {
      default: [
        defineField({
          component: ElRadio,
          props: { value: 'male' },
          slots: { default: defineField({ component: 'span', props: { textContent: t('i18n.gender.male') } }) },
        }),
        defineField({
          component: ElRadio,
          props: { value: 'female' },
          slots: { default: defineField({ component: 'span', props: { textContent: t('i18n.gender.female') } }) },
        }),
        defineField({
          component: ElRadio,
          props: { value: 'other' },
          slots: {
            default: defineField({ component: 'span', props: { textContent: t('i18n.gender.other') } }),
          },
        }),
      ],
    },
  }),
  defineField({
    field: 'suggestion',
    schema: optionalText(),
    span: 12,
    component: ElInput,
    props: {
      clearable: true,
    },
    transform: emptyStringToUndefined,
  }),
  defineField({
    field: 'custom',
    schema: optionalText(),
    span: 12,
    component: ElInput,
    props: {
      clearable: true,
    },
    transform: emptyStringToUndefined,
  }),
])

/**
 * 切换 playground 当前语言。
 *
 * locale 变化会触发表单字段 computed 重建并重新执行 i18n 字段映射。
 */
function toggleLocale() {
  locale.value = locale.value === 'zh-CN' ? 'en-US' : 'zh-CN'
}

/**
 * 展示 i18n 表单提交结果。
 *
 * 提交反馈文案使用当前 locale 的本地文案，不发起远端请求。
 */
function onSubmit(values: Record<string, unknown>) {
  Object.assign(formValues, values)
  alert(`${t('i18n.feedback.submitSuccess')}\n${JSON.stringify(values, null, 2)}`)
}

/**
 * 输出 i18n 表单校验失败结果。
 *
 * 错误前缀使用当前 locale，本体保持 ConfigForm 的字段错误结构。
 */
function onError(errors: Record<string, string[]>) {
  console.error(t('i18n.feedback.validationFailed'), errors)
}

</script>

<template>
  <div>
    <ConfigForm
      ref="formRef"
      :default-values="formValues"
      namespace="moluoxixi"
      :fields="fields"
      :runtime="runtimeOptions"
      label-width="120px"
      @submit="onSubmit"
      @error="onError"
    />

    <div class="demo-actions">
      <el-button @click="toggleLocale">
        {{ t('i18n.action.switchLocale', { locale: nextLocaleLabel }) }}
      </el-button>
      <el-button type="primary" @click="formRef?.submit()">
        {{ t('i18n.action.submit') }}
      </el-button>
      <el-button @click="formRef?.validate()">
        {{ t('i18n.action.validate') }}
      </el-button>
      <el-button @click="formRef?.reset()">
        {{ t('i18n.action.reset') }}
      </el-button>
    </div>

    <el-divider>{{ t('i18n.preview.title') }}</el-divider>
    <pre class="value-preview">{{ JSON.stringify(formValues, null, 2) }}</pre>
  </div>
</template>

<style lang="scss">
.demo-actions {
  margin-top: 16px;
  display: flex;
  gap: 8px;
}

.value-preview {
  background: #f5f7fa;
  border: 1px solid #e4e7ed;
  border-radius: 4px;
  padding: 12px 16px;
  font-size: 12px;
  line-height: 1.6;
  max-height: 300px;
  overflow: auto;
}
</style>
