import { existsSync, mkdirSync, readdirSync, readFileSync, unlinkSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

export interface ComponentRoute {
  name: string
  slug: string
  description: string
}

export interface SyncComponentRoutesOptions {
  root: string
  routeDir: string
  components: ComponentRoute[]
}

export interface SyncComponentRoutesResult {
  generated: string[]
  removed: string[]
  apiOnly: string[]
}

export const GENERATED_ROUTE_MARKER = '<!-- Generated by scripts/extract-api.mts. Do not edit. -->'

const COMPONENT_NAME_PATTERN = /^[A-Z][A-Za-z0-9]*$/
const COMPONENT_SLUG_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/
const LEGACY_ROUTE_PATTERN = /^<!--@include: \.\.\/\.\.\/\.\.\/packages\/components\/src\/[A-Z][A-Za-z0-9]*\/docs\/index\.md-->\r?\n?$/
const API_DOCS_TAG_PATTERN = /<\s*(?:ApiDocs|api-docs)\b/

function sourceDocInclude(component: ComponentRoute): string {
  return `<!--@include: ../../../packages/components/src/${component.name}/docs/index.md-->`
}

function assertSafeComponent(component: ComponentRoute): void {
  if (!COMPONENT_NAME_PATTERN.test(component.name))
    throw new Error(`invalid documentation component name: ${component.name}`)
  if (!COMPONENT_SLUG_PATTERN.test(component.slug))
    throw new Error(`invalid documentation component slug: ${component.slug}`)
  if (component.slug === 'index')
    throw new Error('documentation component slug is reserved: index')
}

function isOwnedRoute(content: string): boolean {
  return content.startsWith(`${GENERATED_ROUTE_MARKER}\n`)
    || content.startsWith(`${GENERATED_ROUTE_MARKER}\r\n`)
    || LEGACY_ROUTE_PATTERN.test(content)
}

export function renderComponentRoute(component: ComponentRoute, hasSourceDoc: boolean): string {
  assertSafeComponent(component)

  const introduction = hasSourceDoc
    ? sourceDocInclude(component)
    : `# ${component.name}\n\n${component.description}`

  return `${GENERATED_ROUTE_MARKER}\n\n${introduction}\n\n## API\n\n<ApiDocs name="${component.name}" />\n`
}

export function syncComponentRoutes(options: SyncComponentRoutesOptions): SyncComponentRoutesResult {
  const { root, routeDir, components } = options
  components.forEach(assertSafeComponent)
  mkdirSync(routeDir, { recursive: true })

  const expectedFiles = new Set(components.map(component => `${component.slug}.md`))
  const routeEntries = readdirSync(routeDir, { withFileTypes: true })
    .filter(entry => entry.name.endsWith('.md') && entry.name !== 'index.md')
  const unsupportedEntries = routeEntries
    .filter(entry => !entry.isFile())
    .map(entry => entry.name)
    .sort()
  if (unsupportedEntries.length > 0)
    throw new Error(`documentation routes contain non-file entries: ${unsupportedEntries.join(', ')}`)

  const existingFiles = routeEntries
    .map(entry => entry.name)

  const collisions: string[] = []
  for (const file of existingFiles) {
    const content = readFileSync(resolve(routeDir, file), 'utf8')
    if (!isOwnedRoute(content))
      collisions.push(file)
  }
  if (collisions.length > 0)
    throw new Error(`documentation routes are not generated files: ${collisions.sort().join(', ')}`)

  const routes = components.map((component) => {
    const sourceDocPath = resolve(root, 'packages/components/src', component.name, 'docs/index.md')
    const hasSourceDoc = existsSync(sourceDocPath)
    if (hasSourceDoc && API_DOCS_TAG_PATTERN.test(readFileSync(sourceDocPath, 'utf8')))
      throw new Error(`component source documentation must not declare ApiDocs: ${component.name}`)

    return {
      component,
      hasSourceDoc,
      content: renderComponentRoute(component, hasSourceDoc),
    }
  })

  const removed: string[] = []
  for (const file of existingFiles) {
    if (expectedFiles.has(file))
      continue
    unlinkSync(resolve(routeDir, file))
    removed.push(file)
  }

  const generated: string[] = []
  const apiOnly: string[] = []
  for (const route of routes) {
    const { component, hasSourceDoc, content } = route
    const routePath = resolve(routeDir, `${component.slug}.md`)

    if (!existsSync(routePath) || readFileSync(routePath, 'utf8') !== content) {
      writeFileSync(routePath, content, 'utf8')
      generated.push(`${component.slug}.md`)
    }
    if (!hasSourceDoc)
      apiOnly.push(component.name)
  }

  return {
    generated: generated.sort(),
    removed: removed.sort(),
    apiOnly: apiOnly.sort(),
  }
}
