import { existsSync, mkdirSync, readdirSync, readFileSync, unlinkSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { stringify } from 'yaml'
import { getLocalizedUtilities } from '../.vitepress/catalog/docs-i18n.ts'
import { docsLocales } from '../.vitepress/site/docs-site.ts'

export const GENERATED_UTILITY_ROUTE_MARKER = '<!-- Generated by scripts/generate-utility-routes.mts. Do not edit directly. -->'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../../..')
const docsRoot = resolve(root, 'docs/vitepress')
let generatedCount = 0

for (const locale of Object.keys(docsLocales) as Array<keyof typeof docsLocales>) {
  const configured = docsLocales[locale]
  const outputDirectory = resolve(docsRoot, configured.sourceDirectory, 'utils')
  const utilities = getLocalizedUtilities(locale)
  const generatedNames = new Set(utilities.map(utility => `${utility.slug}.md`))

  mkdirSync(outputDirectory, { recursive: true })
  for (const utility of utilities) {
    const sourcePath = resolve(root, utility.sourcePath)
    if (!existsSync(sourcePath))
      throw new Error(`utility documentation source does not exist: ${sourcePath}`)

    const outputPath = resolve(outputDirectory, `${utility.slug}.md`)
    if (existsSync(outputPath)) {
      const existing = readFileSync(outputPath, 'utf8')
      if (!existing.includes(GENERATED_UTILITY_ROUTE_MARKER))
        throw new Error(`refusing to overwrite unmanaged utility route: ${outputPath}`)
    }

    const includePath = `${configured.sourceDocIncludePrefix}${utility.sourcePath}`
    const frontmatter = stringify({
      title: utility.packageName,
      description: utility.description,
      outline: [2, 4],
    }, {
      defaultKeyType: 'PLAIN',
      defaultStringType: 'QUOTE_SINGLE',
      lineWidth: 0,
    }).trimEnd()
    const content = [
      '---',
      frontmatter,
      '---',
      '',
      GENERATED_UTILITY_ROUTE_MARKER,
      '',
      `<!--@include: ${includePath}-->`,
      '',
    ].join('\n')

    writeFileSync(outputPath, content, 'utf8')
    generatedCount += 1
  }

  for (const fileName of readdirSync(outputDirectory)) {
    if (fileName === 'index.md' || !fileName.endsWith('.md') || generatedNames.has(fileName))
      continue
    const stalePath = resolve(outputDirectory, fileName)
    if (readFileSync(stalePath, 'utf8').includes(GENERATED_UTILITY_ROUTE_MARKER))
      unlinkSync(stalePath)
  }
}

console.log(`Generated ${generatedCount} searchable utility routes.`)
