import { mkdir } from 'node:fs/promises'
import { expect, test } from '@playwright/test'
import { createProject } from './helpers'

test('Studio commands, editable data and experience state complete a review workflow', async ({ page }) => {
  test.setTimeout(120_000)
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await createProject(page, 'element')
  await expect(page.locator('.studio-issues-dock')).toBeVisible()
  await expect(page.locator('.mx-config-form-designer__selection-spine')).toContainText('profile')
  await page.keyboard.press('Control+k')
  const command = page.getByRole('dialog', { name: 'Command center', exact: true })
  await expect(command).toBeVisible()
  await command.getByRole('combobox').fill('Insert Input')
  await command.getByRole('combobox').press('Enter')
  await expect(command).not.toBeVisible()
  await expect(page.locator('.mx-config-form-designer__properties')).toContainText('Description')
  const separator = page.getByRole('separator', { name: 'Resize inspector' })
  await separator.focus()
  const width = Number(await separator.getAttribute('aria-valuenow'))
  await page.keyboard.press('ArrowLeft')
  await expect(separator).toHaveAttribute('aria-valuenow', String(width + 10))
  await page.keyboard.press('Control+k')
  await command.getByRole('combobox').fill('Manage data')
  await command.getByRole('combobox').press('Enter')
  const assets = page.getByRole('dialog', { name: 'Assets', exact: true })
  await expect(assets).toBeVisible()
  await assets.getByRole('button', { name: 'New Dataset', exact: true }).click()
  await assets.getByRole('tab', { name: 'Import data', exact: true }).click()
  await assets.getByRole('textbox', { name: 'Raw data to import', exact: true }).fill('id,name\n001,Alice\n002,Bob')
  await assets.locator('[data-dataset-ingest-apply]').click()
  await expect(assets.getByRole('textbox', { name: '1 / name', exact: true })).toHaveValue('Alice')
  await assets.getByRole('textbox', { name: '1 / name', exact: true }).fill('Alicia')
  await assets.getByRole('textbox', { name: '1 / name', exact: true }).press('Tab')
  await assets.getByRole('button', { name: 'New Dataset', exact: true }).click()
  await assets.locator('.asset-manager__items').first().getByRole('button').first().click()
  await expect(assets.getByRole('textbox', { name: '1 / name', exact: true })).toHaveValue('Alicia')
  await assets.locator('.el-dialog__headerbtn').click()
  await page.keyboard.press('Control+k')
  await command.getByRole('combobox').fill('Manage data')
  await command.getByRole('combobox').press('Enter')
  await expect(assets.getByRole('textbox', { name: '1 / name', exact: true })).toHaveValue('Alicia')
  await assets.locator('[data-dataset-table-save]').click()
  await assets.getByRole('tab', { name: 'Default projection', exact: true }).click()
  await assets.locator('.el-select__wrapper:has(input[aria-label="Label"])').click()
  await page.getByRole('option', { name: 'name', exact: true }).click()
  await assets.locator('.el-select__wrapper:has(input[aria-label="Value"])').click()
  await page.getByRole('option', { name: 'id', exact: true }).click()
  await expect(assets.locator('[data-dataset-projection-preview]')).toContainText('Alicia')
  await assets.getByRole('button', { name: 'Save projection', exact: true }).click()
  await assets.getByText('Advanced JSON', { exact: true }).click()
  const projection = assets.getByRole('textbox', { name: 'Dataset default projection JSON', exact: true })
  const savedProjection = await projection.inputValue()
  await projection.fill('{"kind":"table","rowKeyPath":["id"],"columns":null}')
  await expect(assets.locator('.dataset-projection-preview')).toContainText('defaultProjection.columns')
  await projection.fill(savedProjection)
  await expect(assets.locator('[data-dataset-projection-preview]')).toContainText('Alicia')
  await assets.locator('.el-dialog__headerbtn').click()
  await page.getByRole('button', { name: 'Show preview', exact: true }).click()
  await expect(page.locator('.experience-inspector')).toBeVisible()
  await expect(page.locator('[data-experience-values]')).toContainText('name')
  const runtime = page.frameLocator('iframe[data-preview-runtime-host]')
  await runtime.locator('[data-field^="name"] input').fill('Review user')
  await expect(page.locator('[data-experience-values]')).toContainText('Review user')
  await page.getByRole('button', { name: 'Reset experience', exact: true }).click()
  await expect(page.locator('[data-experience-values]')).toContainText('name')
  await expect(page.locator('[data-experience-values]')).not.toContainText('Review user')
  await mkdir('dist/studio-review', { recursive: true })
  await page.screenshot({ path: 'dist/studio-review/experience.png', fullPage: true })
  await page.getByRole('button', { name: 'Design', exact: true }).click()
  await page.keyboard.press('Control+k')
  await command.getByRole('combobox').fill('JSON Schema')
  await command.getByRole('combobox').press('Enter')
  const schema = page.getByRole('dialog', { name: 'Generate fields from JSON Schema', exact: true })
  await schema
    .getByRole('textbox', { name: 'JSON Schema', exact: true })
    .fill(
      JSON.stringify({
        type: 'object',
        required: ['reviewEmail'],
        properties: {
          reviewEmail: { type: 'string', title: 'Review email', format: 'email', description: 'Contact for review' },
        },
      }),
    )
  await schema.getByRole('button', { name: 'Review mapping', exact: true }).click()
  await expect(schema).toContainText('Mapping checks passed')
  await schema.locator('[data-schema-apply]').click()
  await expect(schema).not.toBeVisible()
  await expect(
    page.frameLocator('iframe[data-design-runtime-variant="canvas"]').locator('[data-field="reviewEmail"]'),
  ).toContainText('Contact for review')
  await page.getByRole('button', { name: 'Compare responsive layouts', exact: true }).click()
  const compare = page.getByRole('dialog', { name: 'Compare responsive layouts', exact: true })
  await expect(compare.locator('iframe')).toHaveCount(3)
  await compare.getByRole('button', { name: 'Copy layout', exact: true }).click()
  await expect(compare.frameLocator('iframe[title="mobile comparison"]').locator('[data-config-form-responsive-layout]')).toHaveCSS('--mx-config-form-active-columns', '24')
  await compare.locator('.el-dialog__headerbtn').click()
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(page.frameLocator('iframe[data-design-runtime-variant="canvas"]').locator('[data-field="reviewEmail"]')).toHaveCount(1)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(
    page.frameLocator('iframe[data-design-runtime-variant="canvas"]').locator('[data-field="reviewEmail"]'),
  ).toHaveCount(0)
  const form = page.locator('.mx-config-form-designer__properties')
  await form.getByText('Compact', { exact: true }).click()
  const designLayout = page.frameLocator('iframe[data-design-runtime-variant="canvas"]').locator('[data-config-form-responsive-layout]')
  await expect(designLayout).toHaveCSS('gap', '8px')
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(designLayout).toHaveCSS('gap', '16px')
  await page.screenshot({ path: 'dist/studio-review/design.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('tab', { name: 'Canvas', exact: true })).toBeVisible()
  const overflow = await page.evaluate(
    () => document.documentElement.scrollWidth > document.documentElement.clientWidth,
  )
  expect(overflow).toBe(false)
  await page.screenshot({ path: 'dist/studio-review/mobile.png', fullPage: true })
  expect(errors).toEqual([])
})
