import { mkdir } from 'node:fs/promises'
import AxeBuilder from '@axe-core/playwright'
import { expect, test } from '@playwright/test'
import { createProject } from './helpers'

test('Studio commands, editable data and experience state complete a review workflow', async ({ page }) => {
  test.setTimeout(120_000)
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await createProject(page, 'element')
  await expect(page.locator('.studio-issues-dock')).toBeVisible()
  await expect(page.locator('.mx-config-form-designer__selection-spine')).toContainText('profile')
  await page.keyboard.press('Control+k')
  const command = page.getByRole('dialog', { name: 'Command center', exact: true })
  await expect(command).toBeVisible()
  await command.getByRole('combobox').fill('Insert Input')
  await command.getByRole('combobox').press('Enter')
  await expect(command).not.toBeVisible()
  await expect(page.locator('.mx-config-form-designer__properties')).toContainText('Description')
  const separator = page.getByRole('separator', { name: 'Resize inspector' })
  await separator.focus()
  const width = Number(await separator.getAttribute('aria-valuenow'))
  await page.keyboard.press('ArrowLeft')
  await expect(separator).toHaveAttribute('aria-valuenow', String(width + 10))
  await page.keyboard.press('Control+k')
  await command.getByRole('combobox').fill('Manage data')
  await command.getByRole('combobox').press('Enter')
  const assets = page.getByRole('dialog', { name: 'Assets', exact: true })
  await expect(assets).toBeVisible()
  await assets.getByRole('button', { name: 'New Dataset', exact: true }).click()
  await assets.getByRole('tab', { name: 'Import data', exact: true }).click()
  await assets.getByRole('textbox', { name: 'Raw data to import', exact: true }).fill('id,name\n001,Alice\n002,Bob')
  await assets.locator('[data-dataset-ingest-apply]').click()
  await expect(assets.getByRole('button', { name: '1 / name', exact: true })).toHaveText('Alice')
  await assets.getByRole('button', { name: '1 / name', exact: true }).dblclick()
  await assets.getByRole('textbox', { name: '1 / name', exact: true }).fill('Alicia')
  await assets.getByRole('textbox', { name: '1 / name', exact: true }).press('Tab')
  await assets.getByRole('button', { name: 'New Dataset', exact: true }).click()
  await assets.locator('.asset-manager__items').first().getByRole('button').first().click()
  await expect(assets.getByRole('button', { name: '1 / name', exact: true })).toHaveText('Alicia')
  await assets.locator('.el-dialog__headerbtn').click()
  await page.keyboard.press('Control+k')
  await command.getByRole('combobox').fill('Manage data')
  await command.getByRole('combobox').press('Enter')
  await expect(assets.getByRole('button', { name: '1 / name', exact: true })).toHaveText('Alicia')
  await assets.locator('[data-dataset-table-save]').click()
  await assets.getByRole('tab', { name: 'Default projection', exact: true }).click()
  await assets.locator('.el-select__wrapper:has(input[aria-label="Label"])').click()
  await page.getByRole('option', { name: 'name', exact: true }).click()
  await assets.locator('.el-select__wrapper:has(input[aria-label="Value"])').click()
  await page.getByRole('option', { name: 'id', exact: true }).click()
  await expect(assets.locator('[data-dataset-projection-preview]')).toContainText('Alicia')
  await assets.getByRole('button', { name: 'Save projection', exact: true }).click()
  await assets.getByText('Advanced JSON', { exact: true }).click()
  const projection = assets.getByRole('textbox', { name: 'Dataset default projection JSON', exact: true })
  const savedProjection = await projection.inputValue()
  await projection.fill('{"kind":"table","rowKeyPath":["id"],"columns":null}')
  await expect(assets.locator('.dataset-projection-preview')).toContainText('defaultProjection.columns')
  await projection.fill(savedProjection)
  await expect(assets.locator('[data-dataset-projection-preview]')).toContainText('Alicia')
  await assets.locator('.el-dialog__headerbtn').click()
  await page.getByRole('button', { name: 'Show preview', exact: true }).click()
  await expect(page.locator('.experience-inspector')).toBeVisible()
  await expect(page.locator('[data-experience-values]')).toContainText('name')
  const runtime = page.frameLocator('iframe[data-preview-runtime-host]')
  await runtime.locator('[data-field^="name"] input').fill('Review user')
  await expect(page.locator('[data-experience-values]')).toContainText('Review user')
  await page.getByRole('button', { name: 'Reset experience', exact: true }).click()
  await expect(page.locator('[data-experience-values]')).toContainText('name')
  await expect(page.locator('[data-experience-values]')).not.toContainText('Review user')
  await mkdir('dist/studio-review', { recursive: true })
  await page.screenshot({ path: 'dist/studio-review/experience.png', fullPage: true })
  await page.getByRole('button', { name: 'Design', exact: true }).click()
  await page.keyboard.press('Control+k')
  await command.getByRole('combobox').fill('JSON Schema')
  await command.getByRole('combobox').press('Enter')
  const schema = page.getByRole('dialog', { name: 'Generate fields from JSON Schema', exact: true })
  await schema
    .getByRole('textbox', { name: 'JSON Schema', exact: true })
    .fill(
      JSON.stringify({
        type: 'object',
        required: ['reviewEmail'],
        properties: {
          reviewEmail: { type: 'string', title: 'Review email', format: 'email', description: 'Contact for review' },
        },
      }),
    )
  await schema.getByRole('button', { name: 'Review mapping', exact: true }).click()
  await expect(schema).toContainText('Mapping checks passed')
  await schema.locator('[data-schema-apply]').click()
  await expect(schema).not.toBeVisible()
  await expect(
    page.frameLocator('iframe[data-design-runtime-variant="canvas"]').locator('[data-field="reviewEmail"]'),
  ).toContainText('Contact for review')
  await page.getByRole('button', { name: 'Compare responsive layouts', exact: true }).click()
  const compare = page.getByRole('dialog', { name: 'Compare responsive layouts', exact: true })
  await expect(compare.locator('iframe')).toHaveCount(3)
  await compare.getByRole('button', { name: 'Copy layout', exact: true }).click()
  await expect(compare.frameLocator('iframe[title="mobile comparison"]').locator('[data-config-form-responsive-layout]')).toHaveCSS('--mx-config-form-active-columns', '24')
  await compare.locator('.el-dialog__headerbtn').click()
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(page.frameLocator('iframe[data-design-runtime-variant="canvas"]').locator('[data-field="reviewEmail"]')).toHaveCount(1)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(
    page.frameLocator('iframe[data-design-runtime-variant="canvas"]').locator('[data-field="reviewEmail"]'),
  ).toHaveCount(0)
  const form = page.locator('.mx-config-form-designer__properties')
  await form.getByText('Compact', { exact: true }).click()
  const designLayout = page.frameLocator('iframe[data-design-runtime-variant="canvas"]').locator('[data-config-form-responsive-layout]')
  await expect(designLayout).toHaveCSS('gap', '8px')
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(designLayout).toHaveCSS('gap', '16px')
  await page.screenshot({ path: 'dist/studio-review/design.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('tab', { name: 'Canvas', exact: true })).toBeVisible()
  const overflow = await page.evaluate(
    () => document.documentElement.scrollWidth > document.documentElement.clientWidth,
  )
  expect(overflow).toBe(false)
  await page.screenshot({ path: 'dist/studio-review/mobile.png', fullPage: true })
  expect(errors).toEqual([])
})

test('Studio restores searches and keeps command and Inspector navigation usable on desktop and mobile', async ({ page }) => {
  test.setTimeout(120_000)
  await page.goto('/')
  await createProject(page, 'element')
  await page.getByRole('tab', { name: 'Components', exact: true }).click()
  await page.getByRole('button', { name: 'Favorites', exact: true }).click()
  await expect(page.locator('.studio-panel-empty')).toContainText('No favorites yet')
  await page.getByRole('button', { name: 'Browse all components', exact: true }).click()
  const materialSearch = page.getByRole('textbox', { name: 'Search materials', exact: true })
  await expect(materialSearch).toBeFocused()
  await materialSearch.fill('unmatched component')
  await expect(page.locator('.studio-panel-empty')).toContainText('No matching components')
  await page.getByRole('button', { name: 'Clear search', exact: true }).click()
  await expect(page.locator('[data-material-key="element.input"]')).toBeVisible()
  await page.keyboard.press('Control+k')
  const commands = page.getByRole('dialog', { name: 'Command center', exact: true })
  const search = commands.getByRole('combobox')
  await expect(search).toBeFocused()
  await expect(commands.getByRole('option', { selected: true })).toContainText('Switch to design')
  await search.press('ArrowUp')
  await expect(commands.getByRole('option', { selected: true })).toContainText('Element Plus profile form')
  await search.press('ArrowDown')
  await expect(commands.getByRole('option', { selected: true })).toContainText('Switch to design')
  await search.fill('Save project')
  await expect(commands.getByRole('option')).toContainText('All changes are saved.')
  await expect(search).not.toHaveAttribute('aria-activedescendant')
  await search.press('Enter')
  await expect(commands).toBeVisible()
  await search.fill('unmatched command')
  await commands.getByRole('button', { name: 'Show all commands', exact: true }).click()
  await expect(search).toHaveValue('')
  await expect(search).toBeFocused()
  expect((await new AxeBuilder({ page }).include('.studio-command-dialog').withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa']).analyze()).violations).toEqual([])
  await search.press('Tab')
  await expect(commands.getByRole('button', { name: 'Close command center', exact: true })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(commands).toBeHidden()
  await expect(materialSearch).toBeFocused()

  await page.getByRole('tab', { name: 'Layers', exact: true }).click()
  await page.getByRole('textbox', { name: 'Search layers', exact: true }).fill('unmatched layer')
  await expect(page.locator('.studio-panel-empty')).toContainText('No matching layers')
  await page.getByRole('button', { name: 'Clear search', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Search layers', exact: true })).toBeFocused()
  await page.locator('[data-layer-id^="profile-name-"] .designer-layer-select').click()
  const properties = page.locator('.mx-config-form-designer__properties')
  const guidance = properties.locator('[data-property-group="guidance"] button')
  await expect(guidance).toHaveAttribute('aria-expanded', 'false')
  await properties.getByRole('textbox', { name: 'Search properties', exact: true }).fill('description')
  const description = properties.getByRole('textbox', { name: 'Description', exact: true })
  await expect(description).toBeVisible()
  await description.fill('Contact details\nUse your preferred name.')
  await description.press('Tab')
  const runtime = page.frameLocator('iframe[data-design-runtime-variant="canvas"]')
  await expect(runtime.locator('[data-config-node-id^="profile-name-"]')).toContainText('Use your preferred name.')
  await properties.getByRole('button', { name: 'Clear property search', exact: true }).click()
  await expect(properties.getByRole('textbox', { name: 'Search properties', exact: true })).toBeFocused()
  await expect(guidance).toHaveAttribute('aria-expanded', 'false')
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(runtime.locator('[data-config-node-id^="profile-name-"]')).not.toContainText('Use your preferred name.')

  await properties.getByRole('textbox', { name: 'Field', exact: true }).fill('role')
  await properties.getByRole('textbox', { name: 'Field', exact: true }).press('Tab')
  const issues = page.locator('.studio-issues-dock')
  await expect(issues).toHaveAttribute('data-status', 'error')
  await issues.locator('header button').click()
  await expect(issues).toContainText('Field name must be unique: role')
  await issues.getByRole('button', { name: 'Warnings 0', exact: true }).click()
  await expect(issues).toContainText('Other categories still have items to review.')
  await expect(issues).not.toContainText('Checks passed')
  await issues.getByRole('button', { name: 'Show all issues', exact: true }).click()
  expect((await new AxeBuilder({ page }).include('.studio-issues-dock').withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa']).analyze()).violations).toEqual([])
  await issues.getByRole('button', { name: /Field name must be unique: role/ }).click()
  await expect(properties.getByRole('textbox', { name: 'Field', exact: true })).toHaveValue('name')
  await issues.getByRole('button', { name: 'Close issues', exact: true }).click()

  await page.setViewportSize({ width: 390, height: 844 })
  await page.keyboard.press('Control+k')
  await expect(search).toBeFocused()
  await search.fill('unmatched')
  await expect(commands.getByRole('button', { name: 'Show all commands', exact: true })).toBeVisible()
  expect((await new AxeBuilder({ page }).include('.studio-command-dialog').withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa']).analyze()).violations).toEqual([])
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)
  expect(overflow).toBe(false)
  await commands.getByRole('button', { name: 'Close command center', exact: true }).click()
  await page.getByRole('tab', { name: 'Components', exact: true }).click()
  await expect(page.locator('.studio-material-hint')).toBeVisible()
})

test('Projects guide the first visit and let search recover without losing the project list', async ({ page }) => {
  test.setTimeout(120_000)
  await page.goto('/')
  await expect(page.getByText('Create your first project', { exact: true })).toBeVisible()
  await expect(page.locator('.project-manager__overview')).toHaveCount(0)
  await createProject(page, 'element')
  await page.goto('/#/projects')
  await expect(page.locator('[data-project-open]')).toHaveCount(1)
  await page.getByRole('textbox', { name: 'Search projects', exact: true }).fill('Element Plus')
  await expect(page.locator('[data-project-open]')).toHaveCount(1)
  await page.getByRole('textbox', { name: 'Search projects', exact: true }).fill('unmatched project')
  await expect(page.locator('.project-manager__list-heading [role="status"]')).toHaveText('0 of 1 projects')
  await page.getByRole('button', { name: 'Clear search', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Search projects', exact: true })).toBeFocused()
  await page.getByRole('combobox', { name: 'Sort projects', exact: true }).focus()
  await page.getByRole('combobox', { name: 'Sort projects', exact: true }).press('ArrowDown')
  await page.getByRole('option', { name: 'Project name', exact: true }).click()
  await expect(page.locator('.project-manager__sort').getByText('Project name', { exact: true })).toBeVisible()
  await expect(page.locator('.project-card__open-state')).toContainText('Open project')
  expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa']).analyze()).violations).toEqual([])
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.locator('.project-manager__sort')).toBeVisible()
  await expect(page.locator('.project-manager__sort').getByText('Project name', { exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)).toBe(false)
  expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa']).analyze()).violations).toEqual([])
  await page.locator('[data-project-open]').click()
  await expect(page.locator('.page-manager')).toBeVisible()
})
