/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ClipboardCopyError: typeof import('@moluoxixi/components/CopyText')['ClipboardCopyError']
  const antdConfigForm: typeof import('@moluoxixi/components/AntdConfigForm')['antdConfigForm']
  const collectAllConfigFormFields: typeof import('@moluoxixi/components/configForm')['collectAllConfigFormFields']
  const collectConfigFormFields: typeof import('@moluoxixi/components/configForm')['collectConfigFormFields']
  const copyText: typeof import('@moluoxixi/components/CopyText')['copyText']
  const createConfigFormController: typeof import('@moluoxixi/components/configForm')['createConfigFormController']
  const createHeadlessTableRenderer: typeof import('@moluoxixi/components/HeadlessTable')['createHeadlessTableRenderer']
  const createHeadlessTableRendererPlugin: typeof import('@moluoxixi/components/HeadlessTable')['createHeadlessTableRendererPlugin']
  const defineConfigFormField: typeof import('@moluoxixi/components/configForm')['defineConfigFormField']
  const defineConfigFormFields: typeof import('@moluoxixi/components/configForm')['defineConfigFormFields']
  const defineField: typeof import('@moluoxixi/components/configForm')['defineField']
  const defineFields: typeof import('@moluoxixi/components/configForm')['defineFields']
  const defineHeadlessTableRenderer: typeof import('@moluoxixi/components/HeadlessTable')['defineHeadlessTableRenderer']
  const formatConfigFormReadonlyValue: typeof import('@moluoxixi/components/configForm')['formatConfigFormReadonlyValue']
  const formatConfigFormZodIssues: typeof import('@moluoxixi/components/configForm')['formatConfigFormZodIssues']
  const getHeadlessTableColumnId: typeof import('@moluoxixi/components/HeadlessTable')['getHeadlessTableColumnId']
  const getHeadlessTableColumnLabel: typeof import('@moluoxixi/components/HeadlessTable')['getHeadlessTableColumnLabel']
  const getHeadlessTableRawValue: typeof import('@moluoxixi/components/HeadlessTable')['getHeadlessTableRawValue']
  const headlessTableRenderer: typeof import('@moluoxixi/components/HeadlessTable')['headlessTableRenderer']
  const headlessTableRendererKey: typeof import('@moluoxixi/components/HeadlessTable')['headlessTableRendererKey']
  const isConfigFormField: typeof import('@moluoxixi/components/configForm')['isConfigFormField']
  const isConfigFormFieldReadonly: typeof import('@moluoxixi/components/configForm')['isConfigFormFieldReadonly']
  const isConfigFormNodeVisible: typeof import('@moluoxixi/components/configForm')['isConfigFormNodeVisible']
  const isEmptyConfigFormRequiredValue: typeof import('@moluoxixi/components/configForm')['isEmptyConfigFormRequiredValue']
  const normalizeConfigFormValidateOn: typeof import('@moluoxixi/components/configForm')['normalizeConfigFormValidateOn']
  const provideHeadlessTableRenderer: typeof import('@moluoxixi/components/HeadlessTable')['provideHeadlessTableRenderer']
  const resolveConfigFormCondition: typeof import('@moluoxixi/components/configForm')['resolveConfigFormCondition']
  const resolveConfigFormFieldStates: typeof import('@moluoxixi/components/configForm')['resolveConfigFormFieldStates']
  const resolveConfigFormReadonlyRender: typeof import('@moluoxixi/components/configForm')['resolveConfigFormReadonlyRender']
  const shouldValidateConfigFormOn: typeof import('@moluoxixi/components/configForm')['shouldValidateConfigFormOn']
  const useHeadlessTable: typeof import('@moluoxixi/components/HeadlessTable')['useHeadlessTable']
  const validateConfigFormFieldRules: typeof import('@moluoxixi/components/configForm')['validateConfigFormFieldRules']
  const withInstall: typeof import('@moluoxixi/components/configForm')['withInstall']
}
