/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ClipboardCopyError: typeof import('@moluoxixi/components')['ClipboardCopyError']
  const antdConfigForm: typeof import('@moluoxixi/components')['antdConfigForm']
  const collectAllConfigFormFields: typeof import('@moluoxixi/components')['collectAllConfigFormFields']
  const collectConfigFormFields: typeof import('@moluoxixi/components')['collectConfigFormFields']
  const copyText: typeof import('@moluoxixi/components')['copyText']
  const createConfigFormController: typeof import('@moluoxixi/components')['createConfigFormController']
  const createHeadlessTableRenderer: typeof import('@moluoxixi/components')['createHeadlessTableRenderer']
  const defineConfigFormField: typeof import('@moluoxixi/components')['defineConfigFormField']
  const defineConfigFormFields: typeof import('@moluoxixi/components')['defineConfigFormFields']
  const defineField: typeof import('@moluoxixi/components')['defineField']
  const defineFields: typeof import('@moluoxixi/components')['defineFields']
  const defineHeadlessTableRenderer: typeof import('@moluoxixi/components')['defineHeadlessTableRenderer']
  const formatConfigFormReadonlyValue: typeof import('@moluoxixi/components')['formatConfigFormReadonlyValue']
  const formatConfigFormZodIssues: typeof import('@moluoxixi/components')['formatConfigFormZodIssues']
  const getHeadlessTableColumnId: typeof import('@moluoxixi/components')['getHeadlessTableColumnId']
  const getHeadlessTableColumnLabel: typeof import('@moluoxixi/components')['getHeadlessTableColumnLabel']
  const getHeadlessTableRawValue: typeof import('@moluoxixi/components')['getHeadlessTableRawValue']
  const headlessTableRenderer: typeof import('@moluoxixi/components')['headlessTableRenderer']
  const headlessTableRendererKey: typeof import('@moluoxixi/components')['headlessTableRendererKey']
  const isConfigFormField: typeof import('@moluoxixi/components')['isConfigFormField']
  const isConfigFormFieldReadonly: typeof import('@moluoxixi/components')['isConfigFormFieldReadonly']
  const isConfigFormNodeVisible: typeof import('@moluoxixi/components')['isConfigFormNodeVisible']
  const isEmptyConfigFormRequiredValue: typeof import('@moluoxixi/components')['isEmptyConfigFormRequiredValue']
  const normalizeConfigFormValidateOn: typeof import('@moluoxixi/components')['normalizeConfigFormValidateOn']
  const provideHeadlessTableRenderer: typeof import('@moluoxixi/components')['provideHeadlessTableRenderer']
  const resolveConfigFormCondition: typeof import('@moluoxixi/components')['resolveConfigFormCondition']
  const resolveConfigFormFieldStates: typeof import('@moluoxixi/components')['resolveConfigFormFieldStates']
  const resolveConfigFormReadonlyRender: typeof import('@moluoxixi/components')['resolveConfigFormReadonlyRender']
  const shouldValidateConfigFormOn: typeof import('@moluoxixi/components')['shouldValidateConfigFormOn']
  const useHeadlessTable: typeof import('@moluoxixi/components')['useHeadlessTable']
  const validateConfigFormFieldRules: typeof import('@moluoxixi/components')['validateConfigFormFieldRules']
  const withInstall: typeof import('@moluoxixi/components')['withInstall']
}
