export const RUNTIME_HOST_CHANNEL = 'mx-config-form-runtime-host'
export const RUNTIME_HOST_PROTOCOL_VERSION = 5
export const RUNTIME_HOST_MAX_PENDING_ACTIONS = 128
export const RUNTIME_HOST_ACTION_DEADLINE_MS = 10_000
export const RUNTIME_HOST_MAX_PENDING_DATA_REQUESTS = 100
export const RUNTIME_HOST_DATA_DEADLINE_MS = 10_000
