export const FORM_GAP_MAX_PX = 64
export const FORM_LABEL_WIDTH_DEFAULT_PX = 120
export const FORM_LABEL_WIDTH_TABLET_DEFAULT_PX = 96
export const FORM_LABEL_WIDTH_MOBILE_DEFAULT_PX = 72
export const FORM_LABEL_WIDTH_MAX_PX = 480
