import type {
  DesignerDefaultValueKind,
  DesignerLocaleOptions,
  DesignerMaterialDefinition,
  DesignerPropertySetterDefinition,
} from '@moluoxixi/config-form-designer'
import {
  AlignLeft,
  Calendar,
  CheckSquare,
  CircleDot,
  Clock,
  Hash,
  LayoutGrid,
  LayoutPanelTop,
  List,
  ListCollapse,
  PanelBottom,
  PanelsTopLeft,
  Rows3,
  Square,
  ToggleLeft,
  Type as TypeIcon,
} from '@lucide/vue'
import {
  ElCard,
  ElCollapse,
  ElCollapseItem,
  ElDatePicker,
  ElInput,
  ElInputNumber,
  ElSwitch,
  ElTabPane,
  ElTabs,
  ElTimePicker,
} from 'element-plus'
import ElementCheckboxField from './components/ElementCheckboxField.vue'
import ElementRadioField from './components/ElementRadioField.vue'
import ElementSection from './components/ElementSection.vue'
import ElementSelectField from './components/ElementSelectField.vue'
import ElementFlexLayout from './layout/ElementFlexLayout.vue'
import ElementGridLayout from './layout/ElementGridLayout.vue'

interface NumericSetterConstraints {
  min?: number
  max?: number
  step?: number
}

function setter(
  key: string,
  label: string,
  path: string[],
  control: DesignerPropertySetterDefinition['control'],
  options?: DesignerPropertySetterDefinition['options'],
  constraints?: NumericSetterConstraints,
): DesignerPropertySetterDefinition {
  return { key, label, path, control, ...(options ? { options } : {}), ...constraints }
}

function propSetter(
  key: string,
  label: string,
  control: DesignerPropertySetterDefinition['control'],
  options?: DesignerPropertySetterDefinition['options'],
  constraints?: NumericSetterConstraints,
): DesignerPropertySetterDefinition {
  return setter(key, label, ['props', key], control, options, constraints)
}

function defaultValueSetter(
  valueKind: DesignerDefaultValueKind,
  optionsPath?: string[],
): DesignerPropertySetterDefinition {
  return {
    key: 'defaultValue',
    label: 'Default value',
    path: ['defaultValue'],
    control: 'defaultValue',
    valueKind,
    ...(optionsPath ? { optionsPath } : {}),
  }
}

const placeholderSetter = propSetter('placeholder', 'Placeholder', 'text')
const clearableSetter = propSetter('clearable', 'Clearable', 'boolean')
const disabledSetter = propSetter('disabled', 'Disabled', 'boolean')
const optionsSetter = propSetter('options', 'Options', 'options')
const optionDefaults = [
  { label: 'Option A', value: 'a' },
  { label: 'Option B', value: 'b' },
]

function defaultOptions(): typeof optionDefaults {
  return optionDefaults.map(option => ({ ...option }))
}

export const ELEMENT_PLUS_DESIGNER_MATERIALS: DesignerMaterialDefinition[] = [
  {
    key: 'element.input',
    version: 1,
    kind: 'field',
    title: 'Input',
    category: 'Fields',
    icon: TypeIcon,
    runtime: { component: ElInput, readonlyProp: 'readonly' },
    setters: [defaultValueSetter('text'), placeholderSetter, clearableSetter, propSetter('maxlength', 'Max length', 'number', undefined, { min: 0, step: 1 })],
    createNode: ({ id, field = 'input' }) => ({
      id,
      kind: 'field',
      material: 'element.input',
      field,
      label: 'Input',
      props: { placeholder: '' },
    }),
  },
  {
    key: 'element.textarea',
    version: 1,
    kind: 'field',
    title: 'Textarea',
    category: 'Fields',
    icon: AlignLeft,
    runtime: { component: ElInput, readonlyProp: 'readonly' },
    setters: [
      defaultValueSetter('text'),
      placeholderSetter,
      propSetter('rows', 'Rows', 'number', undefined, { min: 1, max: 20, step: 1 }),
      propSetter('maxlength', 'Max length', 'number', undefined, { min: 0, step: 1 }),
    ],
    createNode: ({ id, field = 'textarea' }) => ({
      id,
      kind: 'field',
      material: 'element.textarea',
      field,
      label: 'Textarea',
      props: { type: 'textarea', rows: 3, placeholder: '' },
    }),
  },
  {
    key: 'element.input-number',
    version: 1,
    kind: 'field',
    title: 'Number',
    category: 'Fields',
    icon: Hash,
    runtime: { component: ElInputNumber, readonlyProp: 'disabled' },
    setters: [
      defaultValueSetter('number'),
      propSetter('min', 'Minimum', 'number'),
      propSetter('max', 'Maximum', 'number'),
      propSetter('step', 'Step', 'number', undefined, { min: 0 }),
      propSetter('controls', 'Controls', 'boolean'),
    ],
    createNode: ({ id, field = 'number' }) => ({
      id,
      kind: 'field',
      material: 'element.input-number',
      field,
      label: 'Number',
      props: { step: 1, controls: true },
    }),
  },
  {
    key: 'element.select',
    version: 1,
    kind: 'field',
    title: 'Select',
    category: 'Choices',
    icon: List,
    runtime: { component: ElementSelectField, readonlyProp: 'disabled' },
    setters: [defaultValueSetter('select', ['props', 'options']), placeholderSetter, clearableSetter, propSetter('filterable', 'Filterable', 'boolean'), optionsSetter],
    createNode: ({ id, field = 'select' }) => ({
      id,
      kind: 'field',
      material: 'element.select',
      field,
      label: 'Select',
      props: { options: defaultOptions(), placeholder: '' },
    }),
  },
  {
    key: 'element.radio',
    version: 1,
    kind: 'field',
    title: 'Radio',
    category: 'Choices',
    icon: CircleDot,
    runtime: { component: ElementRadioField, readonlyProp: 'disabled' },
    setters: [defaultValueSetter('select', ['props', 'options']), optionsSetter, disabledSetter],
    createNode: ({ id, field = 'radio' }) => ({
      id,
      kind: 'field',
      material: 'element.radio',
      field,
      label: 'Radio',
      props: { options: defaultOptions() },
    }),
  },
  {
    key: 'element.checkbox',
    version: 1,
    kind: 'field',
    title: 'Checkbox',
    category: 'Choices',
    icon: CheckSquare,
    runtime: { component: ElementCheckboxField, readonlyProp: 'disabled' },
    setters: [defaultValueSetter('multiselect', ['props', 'options']), optionsSetter, disabledSetter],
    createNode: ({ id, field = 'checkbox' }) => ({
      id,
      kind: 'field',
      material: 'element.checkbox',
      field,
      label: 'Checkbox',
      defaultValue: [],
      props: { options: defaultOptions() },
    }),
  },
  {
    key: 'element.switch',
    version: 1,
    kind: 'field',
    title: 'Switch',
    category: 'Choices',
    icon: ToggleLeft,
    runtime: { component: ElSwitch, readonlyProp: 'disabled' },
    setters: [defaultValueSetter('boolean'), propSetter('activeText', 'Active text', 'text'), propSetter('inactiveText', 'Inactive text', 'text')],
    createNode: ({ id, field = 'switch' }) => ({
      id,
      kind: 'field',
      material: 'element.switch',
      field,
      label: 'Switch',
      defaultValue: false,
    }),
  },
  {
    key: 'element.date',
    version: 1,
    kind: 'field',
    title: 'Date',
    category: 'Date & time',
    icon: Calendar,
    runtime: { component: ElDatePicker, readonlyProp: 'readonly' },
    setters: [defaultValueSetter('date'), placeholderSetter, clearableSetter, propSetter('format', 'Display format', 'text')],
    createNode: ({ id, field = 'date' }) => ({
      id,
      kind: 'field',
      material: 'element.date',
      field,
      label: 'Date',
      props: { type: 'date', valueFormat: 'YYYY-MM-DD', placeholder: '' },
    }),
  },
  {
    key: 'element.time',
    version: 1,
    kind: 'field',
    title: 'Time',
    category: 'Date & time',
    icon: Clock,
    runtime: { component: ElTimePicker, readonlyProp: 'readonly' },
    setters: [defaultValueSetter('time'), placeholderSetter, clearableSetter, propSetter('format', 'Display format', 'text')],
    createNode: ({ id, field = 'time' }) => ({
      id,
      kind: 'field',
      material: 'element.time',
      field,
      label: 'Time',
      props: { valueFormat: 'HH:mm:ss', placeholder: '' },
    }),
  },
  {
    key: 'element.section',
    version: 1,
    kind: 'container',
    title: 'Section',
    category: 'Layout',
    icon: LayoutPanelTop,
    runtime: { component: ElementSection },
    setters: [propSetter('title', 'Title', 'text'), propSetter('description', 'Description', 'textarea')],
    slots: [{ name: 'default', title: 'Content', accepts: ['field', 'container'] }],
    createNode: ({ id }) => ({
      id,
      kind: 'container',
      material: 'element.section',
      props: { title: 'Section' },
      slots: { default: [] },
    }),
  },
  {
    key: 'element.card',
    version: 1,
    kind: 'container',
    title: 'Card',
    category: 'Layout',
    icon: Square,
    runtime: { component: ElCard },
    setters: [
      propSetter('header', 'Header', 'text'),
      propSetter('shadow', 'Shadow', 'select', [
        { label: 'Always', value: 'always' },
        { label: 'Hover', value: 'hover' },
        { label: 'Never', value: 'never' },
      ]),
    ],
    slots: [{ name: 'default', title: 'Content', accepts: ['field', 'container'] }],
    createNode: ({ id }) => ({
      id,
      kind: 'container',
      material: 'element.card',
      props: { header: 'Card', shadow: 'never' },
      slots: { default: [] },
    }),
  },
  {
    key: 'element.tabs',
    version: 1,
    kind: 'container',
    title: 'Tabs',
    category: 'Layout',
    icon: PanelsTopLeft,
    runtime: { component: ElTabs },
    setters: [
      propSetter('tabPosition', 'Position', 'select', [
        { label: 'Top', value: 'top' },
        { label: 'Right', value: 'right' },
        { label: 'Bottom', value: 'bottom' },
        { label: 'Left', value: 'left' },
      ]),
      propSetter('stretch', 'Stretch', 'boolean'),
    ],
    slots: [{ name: 'default', title: 'Panes', accepts: ['container'], materials: ['element.tab-pane'] }],
    createNode: ({ id }) => ({
      id,
      kind: 'container',
      material: 'element.tabs',
      props: { tabPosition: 'top' },
      slots: { default: [] },
    }),
  },
  {
    key: 'element.tab-pane',
    version: 1,
    kind: 'container',
    title: 'Tab pane',
    category: 'Layout',
    icon: PanelBottom,
    runtime: { component: ElTabPane },
    setters: [propSetter('label', 'Label', 'text'), propSetter('disabled', 'Disabled', 'boolean')],
    slots: [{ name: 'default', title: 'Content', accepts: ['field', 'container'] }],
    createNode: ({ id }) => ({
      id,
      kind: 'container',
      material: 'element.tab-pane',
      props: { label: 'Tab', name: id },
      slots: { default: [] },
    }),
  },
  {
    key: 'element.collapse',
    version: 1,
    kind: 'container',
    title: 'Collapse',
    category: 'Layout',
    icon: ListCollapse,
    runtime: { component: ElCollapse },
    setters: [propSetter('accordion', 'Accordion', 'boolean')],
    slots: [{ name: 'default', title: 'Items', accepts: ['container'], materials: ['element.collapse-item'] }],
    createNode: ({ id }) => ({
      id,
      kind: 'container',
      material: 'element.collapse',
      props: { accordion: false },
      slots: { default: [] },
    }),
  },
  {
    key: 'element.collapse-item',
    version: 1,
    kind: 'container',
    title: 'Collapse item',
    category: 'Layout',
    icon: PanelBottom,
    runtime: { component: ElCollapseItem },
    setters: [propSetter('title', 'Title', 'text'), propSetter('disabled', 'Disabled', 'boolean')],
    slots: [{ name: 'default', title: 'Content', accepts: ['field', 'container'] }],
    createNode: ({ id }) => ({
      id,
      kind: 'container',
      material: 'element.collapse-item',
      props: { title: 'Item', name: id },
      slots: { default: [] },
    }),
  },
  {
    key: 'element.flex',
    version: 1,
    kind: 'container',
    title: 'Flex Wrap',
    category: 'Layout',
    icon: Rows3,
    runtime: { component: ElementFlexLayout },
    setters: [
      propSetter('direction', 'Direction', 'select', [
        { label: 'Row', value: 'row' },
        { label: 'Column', value: 'column' },
      ]),
      propSetter('wrap', 'Wrap', 'boolean'),
      propSetter('justify', 'Justify', 'select', [
        { label: 'Start', value: 'flex-start' },
        { label: 'Center', value: 'center' },
        { label: 'End', value: 'flex-end' },
        { label: 'Between', value: 'space-between' },
      ]),
      propSetter('align', 'Align', 'select', [
        { label: 'Start', value: 'flex-start' },
        { label: 'Center', value: 'center' },
        { label: 'End', value: 'flex-end' },
        { label: 'Stretch', value: 'stretch' },
      ]),
      propSetter('gap', 'Gap', 'number', undefined, { min: 0, max: 64, step: 4 }),
      propSetter('itemWidth', 'Item width', 'number', undefined, { min: 80, max: 600, step: 20 }),
    ],
    slots: [{ name: 'default', title: 'Content', accepts: ['field', 'container'] }],
    createNode: ({ id }) => ({
      id,
      kind: 'container',
      material: 'element.flex',
      props: { direction: 'row', wrap: true, gap: 12, justify: 'flex-start', align: 'stretch', itemWidth: 220 },
      slots: { default: [] },
    }),
  },
  {
    key: 'element.grid',
    version: 1,
    kind: 'container',
    title: 'Grid',
    category: 'Layout',
    icon: LayoutGrid,
    runtime: { component: ElementGridLayout },
    setters: [
      propSetter('columns', 'Columns', 'number', undefined, { min: 1, max: 12, step: 1 }),
      propSetter('gap', 'Gap', 'number', undefined, { min: 0, max: 64, step: 4 }),
    ],
    slots: [{ name: 'default', title: 'Content', accepts: ['field', 'container'] }],
    createNode: ({ id }) => ({
      id,
      kind: 'container',
      material: 'element.grid',
      props: { columns: 2, gap: 12 },
      slots: { default: [] },
    }),
  },
]

export const ELEMENT_PLUS_DESIGNER_ZH_CN: DesignerLocaleOptions = {
  locale: 'zh-CN',
  messages: {
    'designer.title': '表单设计器',
    'designer.commands': '设计器操作',
    'action.undo': '撤销',
    'action.redo': '重做',
    'action.preview': '预览',
    'action.previewForm': '预览表单',
    'action.import': '导入',
    'action.importDocument': '导入文档',
    'action.export': '导出',
    'action.exportDocument': '导出文档',
    'action.close': '关闭',
    'action.closePreview': '关闭预览',
    'action.cancel': '取消',
    'action.apply': '应用',
    'action.copy': '复制',
    'action.download': '下载',
    'dialog.preview': '表单预览',
    'error.invalidJson': 'JSON 格式无效',
    'error.importFailed': '导入失败',
    'status.ready': '就绪',
    'status.issues': '{count} 个问题{suffix}',
    'palette.materials': '物料',
    'palette.search': '搜索',
    'palette.searchMaterials': '搜索物料',
    'palette.empty': '暂无物料',
    'canvas.form': '表单画布',
    'property.properties': '属性',
    'property.views': '属性视图',
    'property.validation': '校验',
    'property.conditions': '条件',
    'property.diagnostics': '诊断信息',
    'property.form': '表单',
    'property.readonly': '表单只读',
    'property.field': '字段',
    'property.label': '标签',
    'property.span': '栅格宽度',
    'property.rules': '规则',
    'property.inline': '行内布局',
    'property.labelPosition': '标签位置',
    'property.columns': '列数',
    'property.gap': '间距',
    'property.fieldSpan': '字段宽度',
    'default.value': '默认值',
    'default.unset': '未设置',
    'option.left': '左侧',
    'option.top': '顶部',
    'setter.decrease': '减少 {label}',
    'setter.increase': '增加 {label}',
    'switch.on': '开',
    'switch.off': '关',
    'condition.target.visible': '显示',
    'condition.target.hidden': '隐藏',
    'condition.target.required': '必填',
    'condition.target.disabled': '禁用',
    'condition.target.readonly': '只读',
    'condition.mode': '条件模式',
    'condition.off': '关闭',
    'condition.always': '始终',
    'condition.never': '从不',
    'condition.when': '当',
    'condition.custom': '自定义',
    'condition.field': '条件字段',
    'condition.operator': '条件运算符',
    'condition.valueType': '条件值类型',
    'condition.value': '条件值',
    'condition.fieldPlaceholder': '字段名',
    'condition.valuePlaceholder': '值',
    'valueType.text': '文本',
    'valueType.number': '数字',
    'valueType.boolean': '布尔值',
    'valueType.date': '日期',
    'valueType.enum': '枚举',
    'valueType.literal': '字面量',
    'valueType.structured': '结构化',
    'valueType.structuredValue': '结构化值',
    'value.true': '是',
    'value.false': '否',
    'operator.eq': '等于',
    'operator.neq': '不等于',
    'operator.gt': '大于',
    'operator.gte': '大于等于',
    'operator.lt': '小于',
    'operator.lte': '小于等于',
    'operator.in': '属于',
    'operator.contains': '包含',
    'validation.enable': '启用校验',
    'validation.valueType': '值类型',
    'validation.optional': '可选',
    'validation.nullable': '可为空',
    'validation.enumValue': '枚举值 {index}',
    'validation.deleteEnumValue': '删除枚举值 {index}',
    'validation.addValue': '添加值',
    'validation.ruleType': '规则 {index} 类型',
    'validation.deleteRule': '删除规则 {index}',
    'validation.ruleValue': '规则 {index} 值',
    'validation.rulePattern': '规则 {index} 表达式',
    'validation.ruleFlags': '规则 {index} 标志',
    'validation.ruleDate': '规则 {index} 日期',
    'validation.ruleField': '规则 {index} 字段',
    'validation.ruleOperator': '规则 {index} 运算符',
    'validation.ruleKey': '规则 {index} 标识',
    'validation.validatorKey': '校验器标识',
    'validation.flags': '标志',
    'validation.inclusive': '包含边界',
    'validation.ruleMessage': '规则 {index} 文案',
    'validation.customMessage': '自定义文案（可选）',
    'validation.addRule': '添加规则',
    'rule.required': '必填',
    'rule.minLength': '最小长度',
    'rule.maxLength': '最大长度',
    'rule.length': '固定长度',
    'rule.email': '邮箱',
    'rule.url': '网址',
    'rule.uuid': 'UUID',
    'rule.regex': '正则表达式',
    'rule.min': '最小值',
    'rule.max': '最大值',
    'rule.integer': '整数',
    'rule.finite': '有限数值',
    'rule.multipleOf': '倍数',
    'rule.dateMin': '最早日期',
    'rule.dateMax': '最晚日期',
    'rule.compare': '比较字段',
    'rule.custom': '自定义',
    'options.editor': '选项编辑器',
    'options.option': '选项 {index}',
    'options.moveUp': '上移选项 {index}',
    'options.moveDown': '下移选项 {index}',
    'options.delete': '删除选项 {index}',
    'options.labelAria': '选项 {index} 标签',
    'options.valueTypeAria': '选项 {index} 值类型',
    'options.valueAria': '选项 {index} 值',
    'options.add': '添加选项',
    'node.move': '移动',
    'node.moveNode': '移动节点',
    'node.moveUp': '上移',
    'node.moveNodeUp': '上移节点',
    'node.moveDown': '下移',
    'node.moveNodeDown': '下移节点',
    'node.indent': '缩进',
    'node.indentNode': '移入上一个容器',
    'node.outdent': '减少缩进',
    'node.outdentNode': '移出容器',
    'node.copy': '复制',
    'node.copyNode': '复制节点',
    'node.delete': '删除',
    'node.deleteNode': '删除节点',
    'node.select': '选择 {label}',
  },
  materials: {
    'element.input': { title: '输入框', category: '字段', setters: { defaultValue: '默认值', placeholder: '占位文本', clearable: '可清空', maxlength: '最大长度' } },
    'element.textarea': { title: '多行输入', category: '字段', setters: { defaultValue: '默认值', placeholder: '占位文本', rows: '行数', maxlength: '最大长度' } },
    'element.input-number': { title: '数字输入', category: '字段', setters: { defaultValue: '默认值', min: '最小值', max: '最大值', step: '步长', controls: '显示控件' } },
    'element.select': { title: '选择器', category: '选择', setters: { defaultValue: '默认值', placeholder: '占位文本', clearable: '可清空', filterable: '可筛选', options: '选项' } },
    'element.radio': { title: '单选框', category: '选择', setters: { defaultValue: '默认值', options: '选项', disabled: '禁用' } },
    'element.checkbox': { title: '复选框', category: '选择', setters: { defaultValue: '默认值', options: '选项', disabled: '禁用' } },
    'element.switch': { title: '开关', category: '选择', setters: { defaultValue: '默认值', activeText: '开启文案', inactiveText: '关闭文案' } },
    'element.date': { title: '日期', category: '日期时间', setters: { defaultValue: '默认值', placeholder: '占位文本', clearable: '可清空', format: '显示格式' } },
    'element.time': { title: '时间', category: '日期时间', setters: { defaultValue: '默认值', placeholder: '占位文本', clearable: '可清空', format: '显示格式' } },
    'element.section': { title: '分区', category: '布局', setters: { title: '标题', description: '描述' }, slots: { default: '内容' } },
    'element.card': { title: '卡片', category: '布局', setters: { header: '头部', shadow: '阴影' }, options: { shadow: { always: '总是', hover: '悬停', never: '从不' } }, slots: { default: '内容' } },
    'element.tabs': { title: '标签页', category: '布局', setters: { tabPosition: '位置', stretch: '拉伸' }, options: { tabPosition: { top: '顶部', right: '右侧', bottom: '底部', left: '左侧' } }, slots: { default: '面板' } },
    'element.tab-pane': { title: '标签面板', category: '布局', setters: { label: '标签', disabled: '禁用' }, slots: { default: '内容' } },
    'element.collapse': { title: '折叠面板', category: '布局', setters: { accordion: '手风琴模式' }, slots: { default: '面板项' } },
    'element.collapse-item': { title: '折叠项', category: '布局', setters: { title: '标题', disabled: '禁用' }, slots: { default: '内容' } },
    'element.flex': {
      title: 'Flex 换行',
      category: '布局',
      setters: { direction: '方向', wrap: '换行', justify: '主轴对齐', align: '交叉轴对齐', gap: '间距', itemWidth: '项目宽度' },
      options: {
        direction: { row: '横向', column: '纵向' },
        justify: { 'flex-start': '起始', 'center': '居中', 'flex-end': '结束', 'space-between': '两端' },
        align: { 'flex-start': '起始', 'center': '居中', 'flex-end': '结束', 'stretch': '拉伸' },
      },
      slots: { default: '内容' },
    },
    'element.grid': {
      title: 'Grid 栅格',
      category: '布局',
      setters: { columns: '列数', gap: '间距' },
      slots: { default: '内容' },
    },
  },
}
