import type { ConfigFormCondition, ConfigFormNode, DefineConfigFormFieldFactory } from '@moluoxixi/config-form-headless'
import type { ElementFieldKey, ElementKnownValues, ElementOption } from '../types'
import {
  ElAutocomplete,
  ElCascader,
  ElCheckbox,
  ElCheckboxGroup,
  ElColorPicker,
  ElDatePicker,
  ElInput,
  ElInputNumber,
  ElOption,
  ElRadio,
  ElRadioGroup,
  ElRate,
  ElSelect,
  ElSelectV2,
  ElSlider,
  ElSwitch,
  ElTimePicker,
  ElTimeSelect,
  ElTreeSelect,
} from 'element-plus'
import {
  createCheckOptions,
  createFlatOptions,
  createNestedOptions,
  createRadioOptions,
  createSelectV2Options,
  createTreeOptions,
} from './options'

export function createElementKnownValues(seed: string): ElementKnownValues {
  return {
    autocomplete: `${seed} 推荐项`,
    cascader: `${seed}-hangzhou`,
    checkbox: false,
    checkboxGroup: [],
    color: '#409EFF',
    date: '2026-06-01',
    input: '',
    inputNumber: 1,
    radio: 'standard',
    rate: 1,
    select: `${seed}-draft`,
    selectV2: `${seed}-small`,
    slider: 10,
    switchValue: false,
    textarea: '',
    time: '09:00:00',
    timeSelect: '09:00',
    treeSelect: `${seed}-root-a`,
  }
}

export function createElementKnownFields<TValues extends ElementKnownValues>(
  prefix: string,
  withFormItem: boolean,
  defineField: DefineConfigFormFieldFactory<TValues>,
  visible?: ConfigFormCondition<TValues>,
): ConfigFormNode<TValues>[] {
  const suffix = prefix.replace('element-', '')

  return [
    defineField({
      component: ElInput,
      field: 'input' as ElementFieldKey<TValues>,
      id: `${prefix}-input`,
      label: withFormItem ? '文本输入' : undefined,
      props: { 'placeholder': `${prefix} 文本输入`, 'data-testid': `${prefix}-input` },
      span: 12,
      visible,
    }),
    defineField({
      component: ElInput,
      field: 'textarea' as ElementFieldKey<TValues>,
      id: `${prefix}-textarea`,
      label: withFormItem ? '多行文本' : undefined,
      props: { 'placeholder': `${prefix} 多行文本`, 'rows': 2, 'type': 'textarea', 'data-testid': `${prefix}-textarea` },
      span: 24,
      visible,
    }),
    defineField({
      component: ElInputNumber,
      field: 'inputNumber' as ElementFieldKey<TValues>,
      id: `${prefix}-input-number`,
      label: withFormItem ? '数字输入' : undefined,
      props: { 'max': 99, 'min': 0, 'data-testid': `${prefix}-input-number` },
      span: 12,
      visible,
    }),
    defineField({
      component: ElAutocomplete,
      field: 'autocomplete' as ElementFieldKey<TValues>,
      id: `${prefix}-autocomplete`,
      label: withFormItem ? '自动完成' : undefined,
      props: {
        'fetchSuggestions': (_query: string, callback: (items: ElementOption[]) => void) => callback(createFlatOptions(suffix)),
        'placeholder': `${prefix} 自动完成`,
        'teleported': false,
        'data-testid': `${prefix}-autocomplete`,
      },
      span: 12,
      visible,
    }),
    defineField({
      component: ElSelect,
      field: 'select' as ElementFieldKey<TValues>,
      id: `${prefix}-select`,
      label: withFormItem ? '下拉选择' : undefined,
      props: { 'placeholder': `${prefix} 下拉选择`, 'teleported': false, 'data-testid': `${prefix}-select` },
      slots: {
        default: createFlatOptions(suffix).map(option => defineField({
          cellAttrs: {},
          component: ElOption,
          id: `${prefix}-select-option-${String(option.value)}`,
          props: option,
        })),
      },
      span: 12,
      visible,
    }),
    defineField({
      component: ElSelectV2,
      field: 'selectV2' as ElementFieldKey<TValues>,
      id: `${prefix}-select-v2`,
      label: withFormItem ? '虚拟选择' : undefined,
      props: { 'options': createSelectV2Options(suffix), 'placeholder': `${prefix} 虚拟选择`, 'teleported': false, 'data-testid': `${prefix}-select-v2` },
      span: 12,
      visible,
    }),
    defineField({
      component: ElCascader,
      field: 'cascader' as ElementFieldKey<TValues>,
      id: `${prefix}-cascader`,
      label: withFormItem ? '级联选择' : undefined,
      props: { 'options': createNestedOptions(suffix), 'placeholder': `${prefix} 级联选择`, 'props': { emitPath: false }, 'teleported': false, 'data-testid': `${prefix}-cascader` },
      span: 12,
      visible,
    }),
    defineField({
      component: ElTreeSelect,
      field: 'treeSelect' as ElementFieldKey<TValues>,
      id: `${prefix}-tree-select`,
      label: withFormItem ? '树形选择' : undefined,
      props: { 'data': createTreeOptions(suffix), 'placeholder': `${prefix} 树形选择`, 'renderAfterExpand': false, 'teleported': false, 'data-testid': `${prefix}-tree-select` },
      span: 12,
      visible,
    }),
    defineField({
      component: ElCheckbox,
      field: 'checkbox' as ElementFieldKey<TValues>,
      id: `${prefix}-checkbox`,
      label: withFormItem ? '单选勾选' : undefined,
      props: { 'label': `${suffix} 开启`, 'data-testid': `${prefix}-checkbox` },
      span: 12,
      visible,
    }),
    defineField({
      component: ElCheckboxGroup,
      field: 'checkboxGroup' as ElementFieldKey<TValues>,
      id: `${prefix}-checkbox-group`,
      label: withFormItem ? '多选勾选' : undefined,
      props: { 'data-testid': `${prefix}-checkbox-group` },
      slots: {
        default: createCheckOptions(suffix).map(option => defineField({
          cellAttrs: {},
          component: ElCheckbox,
          id: `${prefix}-checkbox-option-${String(option.value)}`,
          props: option,
        })),
      },
      span: 12,
      visible,
    }),
    defineField({
      component: ElSwitch,
      field: 'switchValue' as ElementFieldKey<TValues>,
      id: `${prefix}-switch`,
      label: withFormItem ? '开关' : undefined,
      props: { 'activeText': '开启', 'inactiveText': '关闭', 'data-testid': `${prefix}-switch` },
      span: 12,
      visible,
    }),
    defineField({
      component: ElRadioGroup,
      field: 'radio' as ElementFieldKey<TValues>,
      id: `${prefix}-radio`,
      label: withFormItem ? '单选组' : undefined,
      props: { 'data-testid': `${prefix}-radio` },
      slots: {
        default: createRadioOptions().map(option => defineField({
          cellAttrs: {},
          component: ElRadio,
          id: `${prefix}-radio-option-${String(option.value)}`,
          props: option,
        })),
      },
      span: 12,
      visible,
    }),
    defineField({
      component: ElRate,
      field: 'rate' as ElementFieldKey<TValues>,
      id: `${prefix}-rate`,
      label: withFormItem ? '评分' : undefined,
      props: { 'data-testid': `${prefix}-rate` },
      span: 12,
      visible,
    }),
    defineField({
      component: ElSlider,
      field: 'slider' as ElementFieldKey<TValues>,
      id: `${prefix}-slider`,
      label: withFormItem ? '滑块' : undefined,
      props: { 'max': 100, 'min': 0, 'data-testid': `${prefix}-slider` },
      span: 12,
      visible,
    }),
    defineField({
      component: ElColorPicker,
      field: 'color' as ElementFieldKey<TValues>,
      id: `${prefix}-color`,
      label: withFormItem ? '颜色' : undefined,
      props: { 'predefine': ['#409EFF', '#67C23A', '#E6A23C'], 'teleported': false, 'data-testid': `${prefix}-color` },
      span: 12,
      visible,
    }),
    defineField({
      component: ElDatePicker,
      field: 'date' as ElementFieldKey<TValues>,
      id: `${prefix}-date`,
      label: withFormItem ? '日期' : undefined,
      props: { 'placeholder': `${prefix} 日期`, 'teleported': false, 'type': 'date', 'valueFormat': 'YYYY-MM-DD', 'data-testid': `${prefix}-date` },
      span: 12,
      visible,
    }),
    defineField({
      component: ElTimePicker,
      field: 'time' as ElementFieldKey<TValues>,
      id: `${prefix}-time`,
      label: withFormItem ? '时间' : undefined,
      props: { 'placeholder': `${prefix} 时间`, 'teleported': false, 'valueFormat': 'HH:mm:ss', 'data-testid': `${prefix}-time` },
      span: 12,
      visible,
    }),
    defineField({
      component: ElTimeSelect,
      field: 'timeSelect' as ElementFieldKey<TValues>,
      id: `${prefix}-time-select`,
      label: withFormItem ? '时间选择' : undefined,
      props: { 'end': '12:00', 'placeholder': `${prefix} 时间选择`, 'start': '09:00', 'step': '00:30', 'teleported': false, 'data-testid': `${prefix}-time-select` },
      span: 12,
      visible,
    }),
  ]
}
